// Google Gmail Service — Phase 26
// Send MOM documents and task reminders via Gmail

import { google, Auth } from 'googleapis'
type OAuth2Client = Auth.OAuth2Client

export class GoogleGmailService {
  constructor(private auth: OAuth2Client) {}

  // ── Send MOM document via email ─────────────────────────────────────────────

  async sendMOM(opts: {
    toEmails: string[]
    senderName: string
    meetingTitle: string
    meetingCode: string
    meetingDate: string
    momMarkdown: string
  }): Promise<{ messageId: string }> {
    const gmail = google.gmail({ version: 'v1', auth: this.auth })

    const subject = `Minutes of Meeting — ${opts.meetingTitle} [${opts.meetingCode}]`
    const htmlBody = this.markdownToHTML(opts.momMarkdown, opts.meetingTitle, opts.meetingDate, opts.meetingCode)

    const toList = opts.toEmails.join(', ')
    const message = [
      `To: ${toList}`,
      `Subject: ${subject}`,
      `MIME-Version: 1.0`,
      `Content-Type: text/html; charset=utf-8`,
      ``,
      htmlBody,
    ].join('\n')

    const encoded = Buffer.from(message).toString('base64url')
    const { data } = await gmail.users.messages.send({
      userId: 'me',
      requestBody: { raw: encoded },
    })

    return { messageId: data.id ?? '' }
  }

  // ── Send task reminder email ────────────────────────────────────────────────

  async sendTaskReminder(opts: {
    toEmail: string
    taskTitle: string
    assignedBy: string
    deadline: string
    meetingCode: string
    itemCode?: string
  }): Promise<{ messageId: string }> {
    const gmail = google.gmail({ version: 'v1', auth: this.auth })

    const subject = `Action Item Reminder: ${opts.taskTitle} — Due ${opts.deadline}`
    const body = `
Dear Team Member,

This is a reminder for the following action item from ${opts.meetingCode}:

Task: ${opts.taskTitle}
Assigned by: ${opts.assignedBy}
Deadline: ${opts.deadline}
${opts.itemCode ? `Item Code: ${opts.itemCode}` : ''}

Please update the task status in MOM Pro or contact ${opts.assignedBy} if you need an extension.

Best regards,
MOM Pro — Meeting Intelligence System
`.trim()

    const message = [
      `To: ${opts.toEmail}`,
      `Subject: ${subject}`,
      `MIME-Version: 1.0`,
      `Content-Type: text/plain; charset=utf-8`,
      ``,
      body,
    ].join('\n')

    const encoded = Buffer.from(message).toString('base64url')
    const { data } = await gmail.users.messages.send({
      userId: 'me',
      requestBody: { raw: encoded },
    })

    return { messageId: data.id ?? '' }
  }

  // ── Convert markdown to styled HTML ────────────────────────────────────────

  private markdownToHTML(md: string, title: string, date: string, code: string): string {
    // Simple markdown → HTML conversion (headings, bold, lists)
    const lines = md.split('\n')
    const html: string[] = []

    for (const line of lines) {
      if (line.startsWith('# ')) {
        html.push(`<h1 style="color:#1e40af;border-bottom:2px solid #e0e7ff;padding-bottom:8px">${line.slice(2)}</h1>`)
      } else if (line.startsWith('## ')) {
        html.push(`<h2 style="color:#1e40af;margin-top:20px">${line.slice(3)}</h2>`)
      } else if (line.startsWith('### ')) {
        html.push(`<h3 style="color:#374151">${line.slice(4)}</h3>`)
      } else if (line.startsWith('- ') || line.startsWith('* ')) {
        html.push(`<li style="margin:4px 0">${line.slice(2).replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')}</li>`)
      } else if (line.trim() === '') {
        html.push('<br/>')
      } else {
        html.push(`<p style="margin:6px 0">${line.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')}</p>`)
      }
    }

    return `
<div style="font-family:Arial,sans-serif;max-width:700px;margin:0 auto;color:#1f2937">
  <div style="background:#1e40af;color:white;padding:20px 24px;border-radius:8px 8px 0 0">
    <h1 style="margin:0;font-size:20px">Minutes of Meeting</h1>
    <p style="margin:4px 0 0;opacity:0.8;font-size:13px">${title} · ${date} · ${code}</p>
  </div>
  <div style="background:white;padding:24px;border:1px solid #e5e7eb;border-top:none;border-radius:0 0 8px 8px">
    ${html.join('\n')}
    <hr style="margin:24px 0;border:none;border-top:1px solid #e5e7eb"/>
    <p style="color:#9ca3af;font-size:12px">Generated by MOM Pro — Meeting Intelligence System · Powered by qwen2.5:3b</p>
  </div>
</div>`
  }
}
